import gooogle from '../../assets/google.png'
import slack from '../../assets/slack.png'
import atlassian from '../../assets/atlassian.png'
import gooogle from '../../assets/google.png'
import dropbox from '../../assets/dropbox.png'
